### ISSUE TITLE
Timing for a version compatible with 23R2

### ISSUE THREAD

**Issue by JMcDonnellGFC** [Acumatica/Acumatica-PricingAnalysis#4]
Hello, 
Do you have an idea of timing for a version compatible with 23R2

I get this error trying to publish the 23R1 package on a 23.204.0031 site:
PX.PricingAnalysis.Ext.dll Failed to resolve type reference: PX.Objects.IN.InventoryItem/accrueCost declared in PX.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
PX.PricingAnalysis.Ext.dll Method signature was changed: PX.Objects.IN.InventoryItem PX.Objects.IN.InventoryItem/PK::Find(PX.Data.PXGraph,System.Nullable`1<System.Int32>) declared in PX.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
PX.PricingAnalysis.Ext.dll Method signature was changed: PX.Objects.IN.INItemCost PX.Objects.IN.INItemCost/PK::Find(PX.Data.PXGraph,System.Nullable`1<System.Int32>,System.String) declared in PX.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Validation failed.

**Comment by DhirenChhapgar** [comment]
2023 R2 Compatible version is available now.

**Comment by DhirenChhapgar** [comment]
2023 R2 Compatible version is available now.

**Comment by JMcDonnellGFC** [comment]
Thank you!


Joel McDonnell
Mobile:  +1 630-415-9856
- Private & Confidential -

On Jan 9, 2024, at 7:34 PM, Dhiren Chhapgar ***@***.***> wrote:

﻿

2023 R2 Compatible version is available now.
